version: '3.8'

services:
  server:
    build: .
    ports:
      - "50051:50051"
    command: ["./grpc-server"]

  client:
    build: .
    command: ["./grpc-client"]
    depends_on:
      - server